const Sitemap = () => {

  const sitemapContent = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/about-us</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/legal-services</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/rental-agreement</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/rent-receipts</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/packers-movers</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/painting-cleaning</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/refer-earn</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/summons-notices</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/testimonials</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/careers</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/contact-us</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/faq</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/safety</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/grievance-redressal</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/report-problem</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.4</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/terms-and-conditions</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.3</priority>
  </url>
  <url>
    <loc>https://preview--homehni-com-new23-07-2025-86.lovable.app/privacy-policy</loc>
    <lastmod>2025-01-24</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.3</priority>
  </url>
</urlset>`;

  return (
    <pre style={{ fontFamily: 'monospace', whiteSpace: 'pre-wrap' }}>
      {sitemapContent}
    </pre>
  );
};

export default Sitemap;