-- Populate developer_pages table with all developer data

-- Insert Prestige Group
INSERT INTO developer_pages (
  slug, company_name, logo_url, tagline, description, headquarters, founded_year,
  hero_title, hero_subtitle, highlights,
  specializations, key_projects, awards,
  contact_phone, contact_email, contact_website,
  amenities,
  is_published, is_featured, display_order
) VALUES (
  'prestige-group',
  'Prestige Group',
  '/assets/prestige-group-logo.jpg',
  'Large-scale mixed-use projects, strong presence across South India',
  'Prestige Group is one of India''s leading real estate developers with over 35 years of experience. Known for their premium residential and commercial projects across South India, they have delivered over 280 projects covering 140 million sq ft of developable area.',
  'Bangalore, India',
  '1986',
  'Premium Residential & Commercial Excellence',
  'Delivering World-Class Living Experiences Since 1986',
  'Large-scale mixed-use projects, strong presence across South India',
  '["Premium Residential Projects", "Commercial Complexes", "Mixed-use Developments", "Hospitality Projects", "Retail Spaces"]'::jsonb,
  '["Prestige Lakeside Habitat - Premium residential complex", "Prestige Tech Platina - IT park and commercial space", "Prestige Shantiniketan - Integrated township", "Prestige Golfshire - Golf course community"]'::jsonb,
  '["FIABCI Prix d''Excellence Award", "CNBC Awaaz Real Estate Awards", "Best Developer - South India", "Excellence in Real Estate Development"]'::jsonb,
  '+91 80 4655 5555',
  'info@prestigeconstructions.com',
  'www.prestigeconstructions.com',
  '["Clubhouse", "Swimming Pool", "Fitness Center", "Kids Play Area", "Landscaped Gardens", "24/7 Security"]'::jsonb,
  true,
  false,
  1
)
ON CONFLICT (slug) DO UPDATE SET
  company_name = EXCLUDED.company_name,
  description = EXCLUDED.description,
  updated_at = now();

-- Insert remaining developers
INSERT INTO developer_pages (slug, company_name, logo_url, tagline, description, headquarters, founded_year, hero_title, hero_subtitle, highlights, specializations, key_projects, awards, contact_phone, contact_email, contact_website, amenities, is_published, is_featured, display_order) VALUES
('godrej-properties', 'Godrej Properties', '/assets/godrej-properties-logo.jpg', 'National developer newly active in Hyderabad, high-magnitude projects', 'Godrej Properties is the real estate arm of the Godrej Group, one of India''s most trusted business conglomerates. With a focus on sustainable and innovative development, they have established a strong presence in major Indian cities.', 'Mumbai, India', '1990', 'Sustainable & Innovative Development', 'Building Smart Homes for Modern Living', 'National developer newly active in Hyderabad, high-magnitude projects', '["Sustainable Development", "Smart Homes Technology", "Premium Residential", "Commercial Spaces", "Plotted Developments"]'::jsonb, '["Godrej Park Avenue - Luxury apartments", "Godrej 24 - Premium residential towers", "Godrej Emerald - Green certified homes", "Godrej City - Integrated township"]'::jsonb, '["India Green Building Council Certification", "CREDAI Awards for Excellence", "Best Practices in Sustainability", "Developer of the Year"]'::jsonb, '+91 22 2518 8010', 'marketing@godrejproperties.com', 'www.godrejproperties.com', '["Clubhouse", "Swimming Pool", "Fitness Center", "Kids Play Area", "Landscaped Gardens", "24/7 Security"]'::jsonb, true, false, 2),
('ramky-group', 'Ramky Group', '/assets/ramky-group-logo.jpg', 'Hyderabad-based, focus on sustainable and innovative infrastructure', 'Ramky Group is a diversified infrastructure and real estate development company based in Hyderabad. Known for their innovative approach to urban development and commitment to sustainability, they have been instrumental in shaping Hyderabad''s skyline.', 'Hyderabad, India', '1994', 'Sustainable Infrastructure Development', 'Shaping Hyderabad''s Future', 'Hyderabad-based, focus on sustainable and innovative infrastructure', '["Infrastructure Development", "Sustainable Construction", "Urban Planning", "Residential Communities", "Environmental Solutions"]'::jsonb, '["Ramky One Galaxia - Premium residential", "Ramky One North - Integrated township", "Ramky Towers - Commercial complex", "Ramky Infrastructure Projects"]'::jsonb, '["Green Building Certification", "Excellence in Infrastructure", "Sustainable Development Award", "Best Regional Developer"]'::jsonb, '+91 40 4033 4000', 'info@ramkygroup.com', 'www.ramkygroup.com', '["Clubhouse", "Swimming Pool", "Fitness Center", "Kids Play Area", "Landscaped Gardens", "24/7 Security"]'::jsonb, true, false, 3),
('brigade-group', 'Brigade Group', '/assets/brigade-group-logo.jpg', 'Award-winning developer, active in residential, commercial, hospitality', 'Brigade Group is a leading real estate developer in South India with over 35 years of experience. They are known for their diversified portfolio spanning residential, commercial, retail, and hospitality sectors.', 'Bangalore, India', '1986', 'Diversified Excellence in Real Estate', 'Leading South India''s Development Since 1986', 'Award-winning developer, active in residential, commercial, hospitality', '["Residential Development", "Commercial Projects", "Hospitality Ventures", "Retail Spaces", "Mixed-use Developments"]'::jsonb, '["Brigade Cornerstone Utopia - Premium apartments", "World Trade Center Brigade Gateway", "Brigade Millennium - IT park", "The Sheraton Grand Bangalore Hotel"]'::jsonb, '["CREDAI National Award", "Karnataka State Award", "Best Mixed-use Development", "Excellence in Architecture"]'::jsonb, '+91 80 4137 4000', 'info@brigadegroup.com', 'www.brigadegroup.com', '["Clubhouse", "Swimming Pool", "Fitness Center", "Kids Play Area", "Landscaped Gardens", "24/7 Security"]'::jsonb, true, false, 4),
('aparna-constructions', 'Aparna Constructions', '/assets/aparna-constructions-logo.jpg', 'High-quality housing, tech-enabled, eco-conscious building practices', 'Aparna Constructions is a prominent real estate developer in Hyderabad, known for their commitment to quality construction and innovative design. They have successfully delivered numerous residential and commercial projects across the city.', 'Hyderabad, India', '1996', 'Tech-Enabled Quality Construction', 'Building Modern Homes with Innovation', 'High-quality housing, tech-enabled, eco-conscious building practices', '["Tech-enabled Homes", "Eco-friendly Construction", "Quality Architecture", "Customer-centric Design", "Modern Amenities"]'::jsonb, '["Aparna Sarovar Grande - Luxury villas", "Aparna Cyber Life - IT corridor apartments", "Aparna Hillpark - Gated community", "Aparna Constructions Commercial Hub"]'::jsonb, '["CREDAI Hyderabad Award", "Excellence in Quality Construction", "Best Residential Developer", "Customer Satisfaction Award"]'::jsonb, '+91 40 4020 4040', 'info@aparnaconstructions.com', 'www.aparnaconstructions.com', '["Clubhouse", "Swimming Pool", "Fitness Center", "Kids Play Area", "Landscaped Gardens", "24/7 Security"]'::jsonb, true, false, 5),
('aliens-group', 'Aliens Group', '/assets/aliens-group-logo.jpg', 'Hyderabad-founded, iconic skyscraper projects, design awards', 'Aliens Group is a contemporary real estate developer based in Hyderabad, known for their iconic architectural designs and innovative skyscraper projects. They focus on creating landmark developments that redefine urban living.', 'Hyderabad, India', '2006', 'Iconic Architecture & Design', 'Creating Landmark Developments', 'Hyderabad-founded, iconic skyscraper projects, design awards', '["Iconic Architecture", "Skyscraper Development", "Contemporary Design", "Urban Landmarks", "Premium Living Spaces"]'::jsonb, '["Aliens Space Station Township", "Aliens Hub - Commercial tower", "Aliens Matrix - Residential complex", "Aliens Signature Towers"]'::jsonb, '["Architectural Excellence Award", "Design Innovation Recognition", "Best Upcoming Developer", "Modern Architecture Award"]'::jsonb, '+91 40 2311 1111', 'info@aliensgroup.com', 'www.aliensgroup.com', '["Clubhouse", "Swimming Pool", "Fitness Center", "Kids Play Area", "Landscaped Gardens", "24/7 Security"]'::jsonb, true, false, 6),
('alpine-infratech', 'Alpine Infratech', '/assets/alpine-infratech-logo.png', 'GMR Springfield - Ready to move in 2BHK apartments @ ₹5200/Sft, 47% Open Area', 'Alpine Infratech presents GMR Springfield - Live in Leisure, a premium residential project in Kompally-Bollarum, Hyderabad. Spread across 4 Acres with 4 Blocks (G+5) housing 370 Flats, this ready to move-in project offers 2BHK apartments of 1120 Sft. TS RERA Approved (P02200003938). The project features 47% open area with lavish landscaping and a massive 2420 Sqyd Party Lawn. Bank approved by SBI, HDFC, LIC, Bajaj Finance, and Sundaram Finance.', 'Kompally-Bollarum, Hyderabad', '2008', 'GMR Springfield - Live in Leisure', 'Ready to Move 2BHK Apartments @ ₹5200/Sft', 'GMR Springfield - Ready to move in 2BHK apartments @ ₹5200/Sft, 47% Open Area', '["2BHK - 1120 Sft Apartments", "Ready to Move In", "47% Open Area", "2420 Sqyd Party Lawn", "Bank Approved (SBI, HDFC, LIC, Bajaj, Sundaram)", "Price @ ₹5200/Sft", "1.5 km from Bolaraum MMTS Station", "5 mins to D-Mart & Cineplanet"]'::jsonb, '["GMR Springfield - 4 Acres, 370 Flats, G+5 Blocks", "Location: 1.5 km from Bolaraum MMTS Station", "5 mins drive to D-Mart, Cineplanet, Shopping Malls", "Easy connectivity to Banks, Schools, Hospitals"]'::jsonb, '["TS RERA Approved - P02200003938", "Bank Approvals from SBI, HDFC, LIC", "Bajaj Finance & Sundaram Finance Approved", "Premium Location - Kompally-Bollarum"]'::jsonb, '+91 40 4567 8900', 'info@alpineinfratech.com', 'www.alpineinfratech.com', '["Party Lawn 2420 Sqyd", "Clubhouse", "Landscaped Gardens", "24/7 Security", "Kids Play Area", "Fitness Center"]'::jsonb, true, false, 8)
ON CONFLICT (slug) DO NOTHING;