// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geenmplkdgmlovvgwzai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlZW5tcGxrZGdtbG92dmd3emFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTIzMDQsImV4cCI6MjA2ODgyODMwNH0.ZQTYDsCy6ogC776oU0zakPDCXo_lJpALGVbCNdBlSVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});